name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: 'ubuntu-18.04'

jobs:
- job: run_test
  timeoutInMinutes: 2

  steps:
    - task: UsePythonVersion@0
      displayName: Set python version
      inputs:
        versionSpec: '2.7'
    - script: |
        sudo mkdir -p /etc/assemblyline/
        sudo mkdir -p /var/log/assemblyline/
        sudo cp test/config.yml /etc/assemblyline
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python2-dev
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -e . -r test/requirements.txt
      displayName: Setup environment
    - script: python -m pytest -rsx -vv
      displayName: Test
